version: '1.0'

services:
  db:
    image: postgres:14-alpine
    container_name: fitura_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fitura_online-shop-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=postgres
      - DB_PORT=5432
      - JWT_SECRET=secret_key
      - GMAIL_USER=fituranoreply@gmail.com
      - GMAIL_PASS=falschesPasswort
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fitura_online-shop-frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    restart: unless-stopped

volumes:
  postgres_data: